services:
  forum:
    build: .
    container_name: forum-page
    restart: unless-stopped
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.forum.rule=Host(`forum.marcel.co.nz`)"
        - "traefik.http.routers.forum.entrypoints=websecure"
        - "traefik.http.routers.forum.tls=true"
        - "traefik.http.routers.forum.tls.certresolver=myresolver"
        - "traefik.http.services.forum.loadbalancer.server.port=8000"

        - "traefik.http.middlewares.forum-ratelimit.ratelimit.average=100"
        - "traefik.http.middlewares.forum-ratelimit.ratelimit.burst=50"

        - "traefik.http.middlewares.forum-buffer.buffering.maxRequestBodyBytes=5242880"

        - "traefik.http.routers.forum.middlewares=forum-ratelimit,forum-buffer"
    networks:
      - proxy

networks:
  proxy:
    external: true